export const BRAND_MAPPINGS: Record<string, string[]> = {
  // Banks
  hdfc: ["hdfc", "hdfcbk", "hdfc bank", "hdfc ltd"],
  icici: ["icici", "icicibank", "icici bank"],
  sbi: ["sbi", "state bank", "state bank of india", "sbi bank"],
  axis: ["axis", "axisbank", "axis bank"],
  kotak: ["kotak", "kotak bank", "kotak mahindra", "kmbl"],
  yes: ["yes bank", "yesbank", "yes_bank"],
  pnb: ["pnb", "punjab national bank", "punjab national"],
  bob: ["bob", "bank of baroda", "bankofbaroda"],
  canara: ["canara", "canara bank", "canarabank"],
  union: ["union bank", "unionbank", "union bank of india"],
  idfc: ["idfc", "idfc first", "idfcfirst", "idfc first bank"],
  indusind: ["indusind", "indusind bank", "induslnd"],
  rbl: ["rbl", "rbl bank", "ratnakar bank"],
  city: ["city bank", "citibank", "citi"],
  bandhan: ["bandhan", "bandhan bank", "bandhanbank"],
  au: ["au bank", "au small finance", "au sfd"],
  paytm: ["paytm", "paytm bank", "paytm payments bank", "pytm"],
  cityunion: ["city union bank", "city union", "cub bank"],
  dcb: ["dcb bank", "dcb", "development credit bank"],
  dhanlaxmi: ["dhanlaxmi bank", "dhan laxmi bank", "dhanlaxmi"],
  jkbank: ["j&k bank", "jammu kashmir bank", "jammu and kashmir bank"],
  karnatakabank: ["karnataka bank", "karnatakabank", "kbl"],
  nainitalbank: ["nainital bank", "nainital bank ltd"],
  southindianbank: ["south indian bank", "sib", "southindian bank"],
  tmb: ["tamilnad mercantile bank", "tmb", "tmb bank"],
  idbi: ["idbi bank", "idbi", "industrial development bank"],
  boi: ["bank of india", "boi", "bank of india ltd"],
  bom: ["bank of maharashtra", "bom", "maharashtra bank"],
  centralbank: ["central bank of india", "central bank", "cbi bank"],
  indianbank: ["indian bank", "allahabad bank"],
  iob: ["indian overseas bank", "iob", "iob bank"],
  psb: ["punjab and sind bank", "punjab & sind bank", "psb bank"],
  uco: ["uco bank", "uco", "united commercial bank"],
  esaf: ["esaf small finance bank", "esaf bank", "esaf sfb"],
  ujjivan: ["ujjivan small finance bank", "ujjivan bank", "ujjivan sfb"],
  deutche: ["deutsche bank", "deutsche", "dbs"],
  barclays: ["barclays", "barclays bank", "barclays india"],
  standardchartered: [
    "standard chartered",
    "standardchartered",
    "standard chartered bank",
    "scb",
  ],

  // Payments Banks, Wallets & UPI
  gpay: ["gpay", "google pay", "googlepay", "tez"],
  phonepe: ["phonepe", "phone pe", "phonepay"],
  mobikwik: ["mobikwik", "mobi kwik"],
  freecharge: ["freecharge", "free charge"],
  airtel: ["airtel", "airtel money", "airtel payments bank"],
  jiopayments: ["jio payments", "jio money", "jiomoney"],
  cred: ["cred", "cred pay"],
  slice: ["slice", "slice card"],
  jupiter: ["jupiter", "jupiter money"],
  fi: ["fi money", "fi bank", "epifi"],
  bhim: ["bhim", "bharat interface for money", "bhim upi"],
  whatsapp: ["whatsapp", "whatsapp pay", "whatsapp payments"],
  ippb: ["india post payments bank", "india post payments", "ippb"],
  fino: ["fino payments bank", "fino bank", "fino payments"],

  // Food & Delivery
  swiggy: [
    "swiggy",
    "instamart",
    "swiggy instamart",
    "bundl technologies",
    "toing",
  ],
  zomato: ["zomato", "blinkit", "grofers", "district"],
  dunzo: ["dunzo", "dunzodaily"],
  zepto: ["zepto", "kirana kart"],
  magicpin: ["magicpin", "magic pin", "mpin"],

  // Services & Utilities
  pronto: ["pronto", "pronto daily"],
  snabbit: ["snabbit", "snabbit helper"],
  urbancompany: ["urban company", "urbanclap", "urban company services"],

  // E-commerce
  amazon: [
    "amazon",
    "amzn",
    "amazon india",
    "amazon pay",
    "amazonpay",
    "apay balance",
  ],
  flipkart: ["flipkart", "fkart", "flipkart internet"],
  meesho: ["meesho", "fashnear"],
  myntra: ["myntra"],
  ajio: ["ajio", "reliance ajio"],
  nykaa: ["nykaa", "nykaa fashion", "fsg"],
  bigbasket: ["bigbasket", "big basket", "supermarket grocery"],
  blinkit: ["blinkit", "grofers"],
  jiomart: ["jiomart", "jio mart", "reliance retail"],
  tatacliq: ["tatacliq", "tata cliq", "tata unistore"],

  // Ride & Travel
  ola: ["ola", "ola cabs", "ani technologies"],
  uber: ["uber", "uber india", "uber bv"],
  rapido: ["rapido", "roppen transportation"],
  redbus: ["redbus", "red bus", "ibibo road"],
  irctc: ["irctc", "indian railway", "railway catering"],
  makemytrip: ["makemytrip", "make my trip", "mmt"],
  goibibo: ["goibibo", "go ibibo"],
  cleartrip: ["cleartrip", "clear trip"],
  yatra: ["yatra", "yatra online"],
  airasia: ["airasia", "air asia"],
  indigo: ["indigo", "interglobe", "6e"],
  spicejet: ["spicejet", "spice jet"],
  airindia: ["air india", "airindia"],
  vistara: ["vistara", "tata sia"],

  // Telecom
  vodafone: ["vodafone", "vi", "vodafone idea"],
  bsnl: ["bsnl", "bharat sanchar"],
  tata: ["tata sky", "tata play", "tataplay"],
  act: ["act", "act broadband", "atria convergence"],
  jio: ["jio", "reliance jio", "jio telecom"],

  // Streaming & Entertainment
  netflix: ["netflix", "netflix india"],
  hotstar: [
    "hotstar",
    "disney hotstar",
    "star india",
    "jio star",
    "jiostar",
    "jio cinema",
  ],
  prime: ["prime video", "amazon prime", "primevideo"],
  zee5: ["zee5", "zee entertainment"],
  sonyliv: ["sonyliv", "sony liv", "sony india"],
  spotify: ["spotify"],
  gaana: ["gaana", "times internet"],
  youtube: ["youtube", "yt", "google youtube", "yt music"],
  apple: ["apple", "itunes", "apple music", "app store", "icloud"],
  google: ["google play", "google play store", "play store", "google one"],
  bookmyshow: ["bookmyshow", "book my show", "bms"],
  linkedIn: ["linkedin", "linked in", "microsoft linkedin"],
  instagram: ["instagram"],
  facebook: ["facebook", "meta"],
  twitter: ["twitter", "x corp"],
  chatgpt: ["chatgpt", "openai", "chat gpt"],
  claude: ["claude", "anthropic", "claude ai"],

  // Utilities & Bills
  bescom: ["bescom", "bangalore electricity"],
  mseb: ["mseb", "maharashtra state electricity"],
  tatapower: ["tata power", "tatapower"],
  adani: ["adani", "adani electricity", "adani gas"],
  indane: ["indane", "indian oil", "iocl"],
  hpcl: ["hpcl", "hp gas", "hindustan petroleum"],
  bpcl: ["bpcl", "bharat gas", "bharat petroleum"],

  // Insurance & Finance
  lic: ["lic", "life insurance corporation", "lic india"],
  hdfc_life: ["hdfc life", "hdfclife"],
  icici_pru: ["icici pru", "icici prudential", "icici lombard"],
  bajaj: ["bajaj", "bajaj finserv", "bajaj allianz", "bajaj finance"],
  policybazaar: ["policybazaar", "policy bazaar", "pb fintech"],
  groww: ["groww", "nextbillion"],
  zerodha: ["zerodha", "rainmatter"],
  upstox: ["upstox", "rksv"],
  angelone: ["angel one", "angelone", "angel broking"],
  coin: ["coin by zerodha", "zerodha coin"],

  // Health
  practo: ["practo"],
  apollo: ["apollo", "apollo pharmacy", "apollo hospitals"],
  medplus: ["medplus", "med plus"],
  netmeds: ["netmeds", "reliance netmeds"],
  pharmeasy: ["pharmeasy", "pharm easy", "axelia"],
  tata1mg: ["1mg", "tata 1mg", "one mg"],

  // Education
  byjus: ["byjus", "byju", "think & learn"],
  unacademy: ["unacademy", "sorting hat"],
  upgrad: ["upgrad", "up grad"],
  vedantu: ["vedantu"],
  coursera: ["coursera"],
  udemy: ["udemy"],

  // Retail & Fashion
  reliance: ["reliance", "jiomart", "relianceretail", "reliance fresh"],
  dmart: ["dmart", "d mart", "avenue supermarts"],
  croma: ["croma", "tata croma", "infiniti retail"],
  vijaysales: ["vijay sales", "vijaysales"],

  // Coffee & Dining
  starbucks: ["starbucks", "starbucks india"],
  cafe_coffee: ["cafe coffee day", "ccd", "coffee day"],
  dominos: ["dominos", "domino's", "jubilant foodworks"],
  pizzahut: ["pizza hut", "pizzahut", "ph food"],
  mcdonalds: ["mcdonalds", "mcdonald's", "hardcastle"],
  kfc: ["kfc", "kfc india", "yum restaurants"],
  subway: ["subway"],
  burger_king: ["burger king", "burgerking"],
};
